trigger:
- master

jobs:
- job: FetchPullRequestData
  pool:
    vmImage: ubuntu-16.04

  steps:
  - script: dotnet build src/FetchPullRequestData --configuration Release
    displayName: dotnet build FetchPullRequestData

- job: EDA
  pool:
    vmImage: ubuntu-16.04

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda update -n base -c defaults conda
    displayName: Update to latest conda

  - script: conda env create --quiet --file environment.yml
    displayName: Create conda environment

  - script: |
      source activate a-minute-of-your-time
      jupyter nbconvert --to notebook --execute data-analysis.ipynb
    displayName: Execute Jupyter notebook